apiVersion: v1
kind: Service
metadata:
  name: foobar-service
spec:
  type: NodePort
  selector:
    app: foobar
  ports:
    - protocol: TCP
      port: 2230
      targetPort: 2230
      nodePort: 32123