type: google.api.Service
config_version: 3

http:
  rules:
    - selector: google.longrunning.Operations.GetOperation
      get: /gotmpl/v1/operations/{name}

    - selector: google.longrunning.Operations.DeleteOperation
      delete: /gotmpl/v1/operations/{name}

    - selector: google.longrunning.Operations.CancelOperation
      post: /gotmpl/v1/operations/{name}:cancel
      body: "*"